// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkvp7Vgx6dXmc0__jY5Z2d14qVjN4PjA',
    appId: '1:333666239496:web:ffcc64c061b08332f33dbd',
    messagingSenderId: '333666239496',
    projectId: 'bannabee-b15ef',
    authDomain: 'bannabee-b15ef.firebaseapp.com',
    storageBucket: 'bannabee-b15ef.firebasestorage.app',
    measurementId: 'G-Z6HRGZ7Z2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhldvpALpCn26hEEtd5KM51oGNEnzy5yw',
    appId: '1:333666239496:android:b2553ec2223fb971f33dbd',
    messagingSenderId: '333666239496',
    projectId: 'bannabee-b15ef',
    storageBucket: 'bannabee-b15ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5vD6dQrYEelkN9C2bcneUwOv54pK7c7s',
    appId: '1:333666239496:ios:79feec6802369e4cf33dbd',
    messagingSenderId: '333666239496',
    projectId: 'bannabee-b15ef',
    storageBucket: 'bannabee-b15ef.firebasestorage.app',
    iosBundleId: 'com.example.bannabee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5vD6dQrYEelkN9C2bcneUwOv54pK7c7s',
    appId: '1:333666239496:ios:79feec6802369e4cf33dbd',
    messagingSenderId: '333666239496',
    projectId: 'bannabee-b15ef',
    storageBucket: 'bannabee-b15ef.firebasestorage.app',
    iosBundleId: 'com.example.bannabee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEkvp7Vgx6dXmc0__jY5Z2d14qVjN4PjA',
    appId: '1:333666239496:web:e764406976a5877cf33dbd',
    messagingSenderId: '333666239496',
    projectId: 'bannabee-b15ef',
    authDomain: 'bannabee-b15ef.firebaseapp.com',
    storageBucket: 'bannabee-b15ef.firebasestorage.app',
    measurementId: 'G-GVVWGYCKQB',
  );

}